services:
  server:
    build: server
    volumes:
      - "./server/database.db:/app/database.db"
    ports:
      - "8000:8000"
  client:
    build: client
    ports:
      - "3000:3000"
    environment:
      - "NEXT_PUBLIC_SERVER_URL=https://leonli-inventory-tracker.herokuapp.com"
